taskkill /F /IM "AdobeUpdateService.exe"
taskkill /F /IM "AGSService.exe"
taskkill /F /IM "armsvc.exe"
taskkill /F /IM "CoreSync.exe"
taskkill /F /IM "Adobe Desktop Process.exe"
taskkill /F /IM "Adobe Installer.exe"
taskkill /F /IM "AdobeIPCBroker.exe"
taskkill /F /IM "CCXProcess.exe"
taskkill /F /IM "Creative Cloud Helper.exe"
taskkill /F /IM  "AdobeIPCBroker.exe"
taskkill /F /IM  "AdobeExtensionsService.exe"
